<a href="https://colab.research.google.com/github/Daniel-de-Jesus/Curso-Python-para-Data-Science-e-Machine-Learning/blob/main/Pandas_Dados_ausentes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dados ausentes

Vamos mostrar alguns m√©todos convenientes para lidar com Missing Data em pandas:

In [2]:
import numpy as np
import pandas as pd

In [9]:
#Criando um DataFrame com dados ausentes

df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [10]:
#Retirando as colunas que tenham algum valor NaN
#Nao altera o DataFrame original

df.dropna()

     A    B  C
0  1.0  5.0  1

In [11]:
#Pode-se utilizar essa funcao escolhendo-se uma linha ou coluna

df.dropna(axis=1)

   C
0  1
1  2
2  3

In [13]:
#Tambem podemos utilizar a funcao thresh para selecionar as linhas
#especificando o numero de vezes que queremos que o NaN apareca para elimina-la

#Neste exemplo, apenas as linhas onde o NaN aparecer duas vezes serao eliminadas do DataFrame
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [14]:
#Podemos tambem inserir valores no DataFrame com i .fillna(valor= 'valor')
#que colocarar um valor no lugar de NAN.

df.fillna(value='Conte√∫do')

          A         B  C
0       1.0       5.0  1
1       2.0  Conte√∫do  2
2  Conte√∫do  Conte√∫do  3

In [15]:
# Podemos ustilizar prara limpar os dados no DF de forma mais anal√≠tica
#Como exemplo inserir a media dos dados da coluna na propria coluna
#isto n√£o altera a coluna, mas preenche do valor esperado para os dados


df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64